#ifndef _UI_COMP_SETTINGSCOMPONENT_H
#define _UI_COMP_SETTINGSCOMPONENT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

// COMPONENT settingsComponent
#define UI_COMP_SETTINGSCOMPONENT_SETTINGSCOMPONENT 0
#define UI_COMP_SETTINGSCOMPONENT_SCREEN_TITLE 1
#define UI_COMP_SETTINGSCOMPONENT_BACKLIGHT 2
#define UI_COMP_SETTINGSCOMPONENT_BACKLIGHT_LABEL 3
#define UI_COMP_SETTINGSCOMPONENT_BACKLIGHT_SLIDER 4
#define UI_COMP_SETTINGSCOMPONENT_TFTOFF 5
#define UI_COMP_SETTINGSCOMPONENT_TFTOFF_LABEL 6
#define UI_COMP_SETTINGSCOMPONENT_TFTOFF_SLIDER 7
#define UI_COMP_SETTINGSCOMPONENT_TFTOFF_VALUE 8
#define UI_COMP_SETTINGSCOMPONENT_TFT_INVERT 9
#define UI_COMP_SETTINGSCOMPONENT_TFT_INVERT_LABEL 10
#define UI_COMP_SETTINGSCOMPONENT_TFT_INVERT_INPUT 11
#define UI_COMP_SETTINGSCOMPONENT_PAIR_TITLE 12
#define UI_COMP_SETTINGSCOMPONENT_UNPAIRBUTTON 13
#define UI_COMP_SETTINGSCOMPONENT_RESETSETTINGSBUTTON 14
#define UI_COMP_SETTINGSCOMPONENT_DEVICE_TITLE 15
#define UI_COMP_SETTINGSCOMPONENT_RESETDEVICEBUTTON 16
#define _UI_COMP_SETTINGSCOMPONENT_NUM 17
    lv_obj_t *ui_settingsComponent_create(lv_obj_t *comp_parent);
    void ui_event_comp_settingsComponent_tftInvertInput(lv_event_t *e);
    void ui_event_comp_settingsComponent_resetTouchButton(lv_event_t *e);
    void ui_event_comp_settingsComponent_resetSettingsButton(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
